### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by martoio** [tremckinley/prj-rev-bwfs-dasmoto#1]
Try to keep your lines to between ~80-120 characters. Extremely long lines are harder to read because you need to scroll horizontally. HTML doesn't render any extra line breaks you enter, so you won't need to adjust anything else.

https://github.com/tremckinley/prj-rev-bwfs-dasmoto/blob/db2aaacd4dbfe36692f50dcb13da9d8dc715396c/DasmotoArts/DasmotoArts.html#L17

**Comment by tremckinley** [comment]
Thanks for the tip, I didn't consider how it'd look on a wider screen. my text editor was auto-wrapping.
