### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by martoio** [tremckinley/prj-rev-bwfs-dasmoto#3]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ 
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ 
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4/4
* _Comment(s):_ Good job on using semantic HTML! Most people skip out on that, but you've implemented it nicely.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4/4
* _Comment(s):_ Good job on not having duplicate CSS.
 
### Overall Score: 16/16
Great work! One thing you might want to consider doing is using lowercase letters throughout for your file names, and especially for directories. Also, it's usually good practice to name your main page `index.html`.

Keep up the good work!

**Comment by tremckinley** [comment]
Thank you for the review. I'm looking forward to improving even more!
